Covs/Covs/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('polls/', include('polls.urls', namespace='polls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
]

Covs/polls/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.home, name='home'),
    path('list/', views.polls_list, name='list'),
    path('add/', views.add_poll, name='add'),
    path('results/', views.all_results, name='results'),
    path('edit/<int:poll_id>/', views.edit_poll, name='edit_poll'),
    path('edit/<int:poll_id>/candidate/add/', views.add_candidate, name="add_candidate"),
    path('edit/candidate/<int:candidate_id>/', views.edit_candidate, name="edit_candidate"),
    path('delete/candidate/<int:candidate_id>/', views.delete_candidate, name='candidate_confirm_delete'),
    path('delete/poll/<int:poll_id>/', views.delete_poll, name='poll_confirm_delete'),
    path('details/<int:poll_id>/', views.poll_detail, name='detail'),
    path('details/<int:poll_id>/vote/', views.poll_vote, name='vote')
]

Covs/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.home, name='home'),
    path('list/', views.polls_list, name='list'),
    path('add/', views.add_poll, name='add'),
    path('results/', views.all_results, name='results'),
    path('edit/<int:poll_id>/', views.edit_poll, name='edit_poll'),
    path('edit/<int:poll_id>/candidate/add/', views.add_candidate, name="add_candidate"),
    path('edit/candidate/<int:candidate_id>/', views.edit_candidate, name="edit_candidate"),
    path('delete/candidate/<int:candidate_id>/', views.delete_candidate, name='candidate_confirm_delete'),
    path('delete/poll/<int:poll_id>/', views.delete_poll, name='poll_confirm_delete'),
    path('details/<int:poll_id>/', views.poll_detail, name='detail'),
    path('details/<int:poll_id>/vote/', views.poll_vote, name='vote')
]

Covs/polls/models.py
from django.contrib.auth.models import User
from django.db import models



class Poll(models.Model):
    owner    = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    title     = models.CharField(max_length=255)
    pub_date = models.DateField()
    
    def __str__(self):
        return self.title

  #  This will restrict user from voting more than 
    def user_can_vote(self, user):

    #returns False if user has already voted, else True
        user_votes = user.vote_set.all()
        qs = user_votes.filter(poll=self)
        if qs.exists():
            return False
        return True

#candidate model which is a child model of Poll modle 
class Candidate(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    candidate_name = models.CharField(max_length=255)
    votes = models.IntegerField(default=0)

#returning the form entries
    def __str__(self):
        return"{} = {}".format(self.poll.title[:25], self.candidate_name[:25], sef.candidate_img)


class Vote(models.Model):
    user   = models.ForeignKey(User, on_delete=models.CASCADE)
    poll   = models.ForeignKey(Poll, on_delete=models.CASCADE)
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)

Covs/polls/polls/views.py
from django.contrib  import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse 
import datetime

from .forms import PollForm, EditPollForm, CandidateForm

from .models import Candidate, Poll, Vote


# Create your views here.
def home(request):
    return render(request, 'home.html')


@login_required
def polls_list(request):
                
            #    Renders the pools_list.html template which has 
            #    the list of all the currently available polls
    if not request.user.is_authenticated:
        return redirect('{}?next={}'.format(settings.LOGIN_URL, request.path))
    polls = Poll.objects.all()
    context = {'polls': polls}
    return render(request, 'polls/polls_list.html', context)

@login_required
def add_poll(request):
    if request.method =="POST":
        form = PollForm(request.POST)
        if form.is_valid():
            new_poll = form.save(commit=False)
            new_poll.pub_date = datetime.datetime.now()
            new_poll.owner = request.user
            new_poll.save()
            new_candidate1 = Candidate(
                            poll = new_poll,
                            candidate_name = form.cleaned_data['candidate1']
                            ).save()
            new_candidate2 = Candidate(
                            poll = new_poll,
                            candidate_name = form.cleaned_data['candidate2']
                            ).save()
            messages.success(
                request, 
                'Poll and candidates added!',
                extra_tags='alert alert-success alert-dismissible fade show'
                )
            return redirect('polls:list')
    else:
        form = PollForm()
    context = {'form': form}
    return render(request, 'polls/add_poll.html', context)


@login_required
def delete_poll(request,  poll_id):
    poll   = get_object_or_404(Poll, id=poll_id)
    if request.user != poll.owner:
        return redirect('/')

    if request.method == "POST":
             poll.delete()
             messages.success(
                             request,
                             'Poll Deleted Successfully',
                             extra_tags='alert alert-success alert-dismissible fade show'
                             )
             return redirect('polls:list')
    
    return render(request, 'polls/delete_poll_confirm.html', { 'poll':poll })


@login_required
def edit_poll(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    if request.user != poll.owner:
        return redirect('/')
    
    if request.method == "POST":
         form = EditPollForm(request.POST, instance=poll)

         if form.is_valid():
             form.save()
             messages.success(
                             request,
                             'Poll Edit Successfull',
                             extra_tags='alert alert-success alert-dismissible fade show'
                             )
             return redirect('polls:list')
    else:
        form = EditPollForm(instance=poll)
    
    return render(request, 'polls/edit_poll.html', {'form':form, 'poll':poll })

@login_required
def add_candidate(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    if request.user != poll.owner:
        return redirect('/')
    
    if request.method == "POST":
         form = CandidateForm(request.POST)
         if form.is_valid():
             new_candidate = form.save(commit=False)
             new_candidate.poll = poll
             new_candidate.save()
             messages.success(
                             request,
                             'candidate Added Successfully',
                             extra_tags='alert alert-success alert-dismissible fade show'
                             )
             return redirect('polls:list')
    else:
        form = CandidateForm() 
    return render(request, 'polls/add_candidate.html', {'form': form})

@login_required
def edit_candidate(request, candidate_id):
    candidate = get_object_or_404(candidate, id=candidate_id)
    poll   = get_object_or_404(Poll, id=candidate.poll.id)
    if request.user != poll.owner:
        return redirect('/')
    
    if request.method == "POST":
         form = CandidateForm(request.POST, instance=candidate)
         if form.is_valid():
             form.save()
             messages.success(
                             request,
                             'candidate Edited Successfully',
                             extra_tags='alert alert-success alert-dismissible fade show'
                             )
             return redirect('polls:list')
    else:
        form = CandidateForm(instance=candidate)
    return render(request, 'polls/add_candidate.html', {'form':form, 'edit_mode': True, 'candidate':candidate})

@login_required
def delete_candidate(request, candidate_id):
    candidate = get_object_or_404(candidate, id=candidate_id)
    poll   = get_object_or_404(Poll, id=candidate.poll.id)
    if request.user != poll.owner:
        return redirect('/')

    if request.method == "POST":
             candidate.delete()
             messages.success(
                             request,
                             'candidate Deleted Successfully',
                             extra_tags='alert alert-success alert-dismissible fade show'
                             )
             return redirect('polls:list')
    
    return render(request, 'polls/delete_candidate_confirm.html', { 'candidate':candidate })

@login_required
def poll_detail(request, poll_id):

            #    Render the poll_detail.html template
            #     which allows a user to vote on th candidates of a poll

            # poll = Poll.objects.get(id=poll_id)
                

    poll = get_object_or_404(Poll,id=poll_id)
    user_can_vote = poll.user_can_vote(request.user)
    context = { 'poll':poll, 'user_can_vote':user_can_vote}
    return render(request, 'polls/poll_detail.html', context)

def poll_vote(request, poll_id):
    poll = get_object_or_404(Poll,id=poll_id)
    if not poll.user_can_vote(request.user):
         messages.error(request,
                             'Can not vote more than once, already voted for ',
                             extra_tags='alert alert-danger  alert-dismissible fade show'
                             )
         return HttpResponseRedirect(reverse("polls:detail", args=(poll_id,)))

    candidate_id = request.POST.get('candidate')
    if candidate_id:
        candidate = Candidate.objects.get(id=candidate_id)
        new_vote =Vote(user=request.user, poll=poll, candidate=candidate)
        new_vote.save()
        candidate.votes += 1
        candidate.save()
    else:
        messages.error(request,'You have not yet voted for ')
        return HttpResponseRedirect(reverse("polls:detail", args=(poll_id,)))
    return redirect('polls:list')

def all_results(request):
    polls = Poll.objects.all()
    context = {'polls': polls}
    return render(request, 'polls/results.html', context)

Covs/polls/views.py
from django.contrib  import messages
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse 
import datetime

from .forms import PollForm, EditPollForm, CandidateForm

from .models import Candidate, Poll, Vote


# Create your views here.
def home(request):
    return render(request, 'home.html')


@login_required
def polls_list(request):
                
            #    Renders the pools_list.html template which has 
            #    the list of all the currently available polls
    if not request.user.is_authenticated:
        return redirect('{}?next={}'.format(settings.LOGIN_URL, request.path))
    polls = Poll.objects.all()
    context = {'polls': polls}
    return render(request, 'polls/polls_list.html', context)

@login_required
def add_poll(request):
    if request.method =="POST":
        form = PollForm(request.POST)
        if form.is_valid():
            new_poll = form.save(commit=False)
            new_poll.pub_date = datetime.datetime.now()
            new_poll.owner = request.user
            new_poll.save()
            new_candidate1 = Candidate(
                            poll = new_poll,
                            candidate_name = form.cleaned_data['candidate1']
                            ).save()
            new_candidate2 = Candidate(
                            poll = new_poll,
                            candidate_name = form.cleaned_data['candidate2']
                            ).save()
            messages.success(
                request, 
                'Poll and candidates added!',
                extra_tags='alert alert-success alert-dismissible fade show'
                )
            return redirect('polls:list')
    else:
        form = PollForm()
    context = {'form': form}
    return render(request, 'polls/add_poll.html', context)


@login_required
def delete_poll(request,  poll_id):
    poll   = get_object_or_404(Poll, id=poll_id)
    if request.user != poll.owner:
        return redirect('/')

    if request.method == "POST":
             poll.delete()
             messages.success(
                             request,
                             'Poll Deleted Successfully',
                             extra_tags='alert alert-success alert-dismissible fade show'
                             )
             return redirect('polls:list')
    
    return render(request, 'polls/delete_poll_confirm.html', { 'poll':poll })


@login_required
def edit_poll(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    if request.user != poll.owner:
        return redirect('/')
    
    if request.method == "POST":
         form = EditPollForm(request.POST, instance=poll)

         if form.is_valid():
             form.save()
             messages.success(
                             request,
                             'Poll Edit Successfull',
                             extra_tags='alert alert-success alert-dismissible fade show'
                             )
             return redirect('polls:list')
    else:
        form = EditPollForm(instance=poll)
    
    return render(request, 'polls/edit_poll.html', {'form':form, 'poll':poll })

@login_required
def add_candidate(request, poll_id):
    poll = get_object_or_404(Poll, id=poll_id)
    if request.user != poll.owner:
        return redirect('/')
    
    if request.method == "POST":
         form = CandidateForm(request.POST)
         if form.is_valid():
             new_candidate = form.save(commit=False)
             new_candidate.poll = poll
             new_candidate.save()
             messages.success(
                             request,
                             'candidate Added Successfully',
                             extra_tags='alert alert-success alert-dismissible fade show'
                             )
             return redirect('polls:list')
    else:
        form = CandidateForm() 
    return render(request, 'polls/add_candidate.html', {'form': form})

@login_required
def edit_candidate(request, candidate_id):
    candidate = get_object_or_404(candidate, id=candidate_id)
    poll   = get_object_or_404(Poll, id=candidate.poll.id)
    if request.user != poll.owner:
        return redirect('/')
    
    if request.method == "POST":
         form = CandidateForm(request.POST, instance=candidate)
         if form.is_valid():
             form.save()
             messages.success(
                             request,
                             'candidate Edited Successfully',
                             extra_tags='alert alert-success alert-dismissible fade show'
                             )
             return redirect('polls:list')
    else:
        form = CandidateForm(instance=candidate)
    return render(request, 'polls/add_candidate.html', {'form':form, 'edit_mode': True, 'candidate':candidate})

@login_required
def delete_candidate(request, candidate_id):
    candidate = get_object_or_404(candidate, id=candidate_id)
    poll   = get_object_or_404(Poll, id=candidate.poll.id)
    if request.user != poll.owner:
        return redirect('/')

    if request.method == "POST":
             candidate.delete()
             messages.success(
                             request,
                             'candidate Deleted Successfully',
                             extra_tags='alert alert-success alert-dismissible fade show'
                             )
             return redirect('polls:list')
    
    return render(request, 'polls/delete_candidate_confirm.html', { 'candidate':candidate })

@login_required
def poll_detail(request, poll_id):

            #    Render the poll_detail.html template
            #     which allows a user to vote on th candidates of a poll

            # poll = Poll.objects.get(id=poll_id)
                

    poll = get_object_or_404(Poll,id=poll_id)
    user_can_vote = poll.user_can_vote(request.user)
    context = { 'poll':poll, 'user_can_vote':user_can_vote}
    return render(request, 'polls/poll_detail.html', context)

def poll_vote(request, poll_id):
    poll = get_object_or_404(Poll,id=poll_id)
    if not poll.user_can_vote(request.user):
         messages.error(request,
                             'Can not vote more than once, already voted for ',
                             extra_tags='alert alert-danger  alert-dismissible fade show'
                             )
         return HttpResponseRedirect(reverse("polls:detail", args=(poll_id,)))

    candidate_id = request.POST.get('candidate')
    if candidate_id:
        candidate = Candidate.objects.get(id=candidate_id)
        new_vote =Vote(user=request.user, poll=poll, candidate=candidate)
        new_vote.save()
        candidate.votes += 1
        candidate.save()
    else:
        messages.error(request,'You have not yet voted for ')
        return HttpResponseRedirect(reverse("polls:detail", args=(poll_id,)))
    return redirect('polls:list')

def all_results(request):
    polls = Poll.objects.all()
    context = {'polls': polls}
    return render(request, 'polls/results.html', context)

Covs/polls/polls/templates/polls/add_candidate.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
   <h1 class="text-center">
         {% if edit_mode %}
         Edit the Candidate
         {% else %}
         Add Candidate
         {% endif %}  </h1>
   <div class="row">
     <div class="col-sm-6 offset-sm-3">
       <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
         <div class="">
          {{ field.errors }}
          {{ field.label_tag }}
          {{ field }}
         </div>
         {% endfor %}
       <input type="submit" value="submit" class="btn btn-primary">
       
       {% if edit_mode %}
         <a href="{% url 'polls:candidate_confirm_delete' candidate.id %}"
           class="btn btn-danger">
           <i class="far fa-trash-alt"></i>Delete
         </a>
       {% endif %}

       </form>
     </div>
   </div>
 </div>
{% endblock content %}

Covs/polls/polls/templates/polls/add_poll.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
      <div class="row ">
      <div class="col-md-6 offset-sm-2">
         <h1 class="text-center">Add  Poll </h1>
           <form action="" method="post">
                {% csrf_token %}
                {% for field in  form %}
                  <div class="form-group">
                  {{ field.errors }}
                  {{ field.label_tag }}
                  {{ field }}
                  </div>
                {% endfor %}
                  <input class="btn btn-primary" type="submit" value="submit">
            </form>
      </div>
      </div>
</div>

{% endblock content %}
      

Covs/polls/polls/templates/polls/delete_candidate_confirm.html
 {% extends 'base.html' %}

 {% block content %}
    <div class="container">
       <div class="row">
          <div class="col-sm-6 offset-sm-3 text-center">
            <form action="" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="hope you know what you doing">
            </form>
          </div>
       </div>
    </div>

 {% endblock content %}

Covs/polls/polls/templates/polls/delete_poll_confirm.html
 {% extends 'base.html' %}

 {% block content %}
    <div class="container">
       <div class="row">
          <div class="col-sm-6 offset-sm-3 text-center">
            <form action="" method="post">
                {% csrf_token %}
                <input type="submit" class="btn btn-danger" value="Click to permanently delete the Poll">
             </form>
          </div>
        </div>
    </div>

 {% endblock content %}

Covs/polls/polls/templates/polls/edit_poll.html
{% extends 'base.html' %}

{% block content %}


<div class="container">
   <h3 class="text-center">Edit Poll</h3>
   <div class="row">
     <div class="col-sm-6 offset-sm-3">
       <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
         <div class="">
          {{ field.errors }}
          {{ field.label_tag }}
          {{ field }}
         </div>
         {% endfor %}
       <input type="submit" value="submit" class="btn btn-primary">
       <a href="{% url 'polls:add_candidate' poll.id %}"  class="btn btn-warning">Add Candidate</a>
       <a href="{% url 'polls:poll_confirm_delete' poll.id %}"
           class="btn btn-danger">
           <i class="far fa-trash-alt"></i>Delete
        </a>
       </form>

       <h3 class="text-center">Candidate</h3>
       {% for candidate in poll.candidate_set.all %}
       <p><a href="{% url 'polls:edit_candidate' candidate.id %}" class="float-right"><i class="fas fa-pencil-alt">Edit</i><a/>{{candidate.candidate_name}}</p>
       {% endfor %}

     </div>
   </div>
 </div>
{% endblock content %}

Covs/polls/polls/templates/polls/poll_detail.html
{% extends 'base.html' %}
{% block content %}

{% if messages %}
    <ul class="messages">
    {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}{{poll}}</li>
    {% endfor %}
    </ul>
{% endif %}

<h2>Poll Detail Page</h2>

{{poll}}

<form action="{% url 'polls:vote' poll.id%}" method="post">
 {% csrf_token %}
 {% for candidate in poll.candidate_set.all %}
 
 <input type="radio"
        name="candidate"
        id="candidate{{forloop.counter }}"
        value= "{{ candidate.id }}"/>

 <lable for="candidate{{ forloop.counter }}">{{ candidate.candidate_name }}</lable>
 <br/>

 {% endfor %}

 <input type="submit" value="Vote" {% if not user_can_vote %}disabled{% endif %} />

</form>
 
{% endblock content %}

Covs/polls/polls/templates/polls/polls_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1 class="text-center"> Welcome to the Poll list </h1>
      <div class="row ">
            <div class="col-md-6 offset-sm-3">

             {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                      {{ message }}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                {% endfor %}
            {% endif %}
                    {% if request.user.is_staff %}
                      <a href="{% url 'polls:add' %}" class="btn btn-primary" style="margin-bottom: 5px">Add <i class="fas fa-plus"></i> </a>
                    {% endif %}
                <ul class="list-group">
                    {% for poll in polls %}
                    <li class="list-group-item">
                         {% if request.user.is_staff %}
                           <a href="{% url 'polls:detail' poll.id %}">{{ poll }}</a>
                          <a href="{% url 'polls:edit_poll' poll.id %}" class="float-right"><i class="fas fa-pencil-alt">Edit</i><a/>
                          {% else %}
                          {{ poll }}
                           <a href="{% url 'polls:detail' poll.id %} " class="float-right btn btn-primary">Vote</a>
                         {% endif %}
                    </li>
                    {% endfor %}
                </ul>
            </div>
      </div>
</div>
{% endblock content %}

Covs/polls/polls/templates/polls/polls_results.html
{% extends 'base.html' %}

{% block content %}


<div class="container">
    <div class="row">
       <div class="col">
            {% if messages %}
                <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
            <ul>
                {% for candidate in poll.candidate_set.all %}
                  <li> {{ candidate.candidate_name }} - {{ candidate.votes }} </li>
                {% endfor %}
            </ul>
       </div>
    </div>
</div>

{% endblock content %}


{% comment %} 

 Realtime feed of the ongoing voting process

    {% for poll in polls %}
        <li><a href="{% url 'polls:detail' poll.id %}">{{ poll }}</a></li>
            <ul>
                {% for candidate in poll.candidate_set.all %}
                  <li> {{ candidate.candidate_name }} - {{ candidate.votes }} </li>
                {% endfor %}
            </ul>
    {% endfor %}
    
{% endcomment %}

Covs/polls/polls/templates/polls/results.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1 class="text-center"> The Race Continues WHO becomes What</h1>
    <h3 class="text-center"> Its the Comrades Voices </h3>
      <div class="row ">
            <div class="col-md-6 offset-sm-3">

             {% if messages %}
                {% for message in messages %}
                    <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                      {{ message }}
                      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                {% endfor %}
            {% endif %}
                <ul class="list-group text-center">
                     {% for poll in polls %}
                        <li class="list-group-item">
                            <p style="color:green;">{{ poll }}</p> <br>
                            {% for candidate in poll.candidate_set.all %}
                                {{ candidate.candidate_name }} = {{ candidate.votes }}<br>
                            {% endfor %}
                        </li>
                    {% endfor %}
                </ul>
            </div>
      </div>
</div>
{% endblock content %}